name: docker-release
on: 
  [ push, delete, create ]
#   schedule:
#     - cron: 1 */3
jobs:
  docker-release:
    name: Release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login docker hub
        run: |
          docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PWD }}
      - name: build and push image
        run: |
          bash docker-release.sh
